AnamergerMain:
    TreeName: mergedBeta
    MergerListName: "/home/msingh9/vandle18/YSO_trace_analysis/vandleDump/Ni78.txt"
    NumWorkers: 20
    PrintFrequency: 10000
    UseProof: True
    #NumEntries: 10000
    #FirstEntry: 0
