RunSetting:
    TChainFlag: False
    PrintFrequency: 100000
    InitalEvent: 0
    #NumEvents: 10000

TraceAnalyzer:
    ChannelOutput: False
    ChannelList:
      - Channel:
          TreeName: "dynode_high"
          SubtypeName: "dynode_high"
          TagName: "ignore"
      - Channel:
          TreeName: "xa_high"
          SubtypeName: "anode_high"
          TagName: "xa"
      - Channel:
          TreeName: "xb_high"
          SubtypeName: "anode_high"
          TagName: "xb"
      - Channel:
          TreeName: "ya_high"
          SubtypeName: "anode_high"
          TagName: "ya"
      - Channel:
          TreeName: "yb_high"
          SubtypeName: "anode_high"
          TagName: "yb"
      - Channel:
          TreeName: "dynode_low"
          SubtypeName: "dynode_low"
          TagName: "ignore"
      - Channel:
          TreeName: "xa_low"
          SubtypeName: "anode_low"
          TagName: "xa"
      - Channel:
          TreeName: "xb_low"
          SubtypeName: "anode_low"
          TagName: "xb"
      - Channel:
          TreeName: "ya_low"
          SubtypeName: "anode_low"
          TagName: "ya"
      - Channel:
          TreeName: "yb_low"
          SubtypeName: "anode_low"
          TagName: "yb"
      - Channel:
          TreeName: "veto_first"
          SubtypeName: "veto"
          TagName: "1"
      - Channel:
          TreeName: "veto_second"
          SubtypeName: "veto"
          TagName: "2"
      - Channel:
          TreeName: "ion_white"
          SubtypeName: "ion"
          TagName: "white"
      - Channel:
          TreeName: "ion_green"
          SubtypeName: "ion"
          TagName: "green"
      - Channel:
          TreeName: "ion_blue"
          SubtypeName: "ion"
          TagName: "blue"
      - Channel:
          TreeName: "ion_black"
          SubtypeName: "ion"
          TagName: "black"
      - Channel:
          TreeName: "dynode_singles"
          SubtypeName: "dynode_high"
          TagName: "singles"

PspmtAnalyzer:
    TreeName: "pspmt"

    ### Output branches (False by default)
    
    #BATO:       True
    #CLOVER:     True
    #DOUBLEBETA: True
    #GAMMASCINT: True
    #LOGIC:      True
    #NEXT:       True
    PID:        True
    #ROOTDEV:    True
    #SINGLEBETA: True
    VANDLE:     True

    TimeWindow: 160 # in ns
    TimeOffset: 0
    TimeWindowIon: 150
    TimeOffsetIon: -50
    TimeWindowVeto: 150
    TimeOffsetVeto: -50
    HighGainThreshold: -100
    HighGainOverflow:  65535
    LowGainThreshold: -900
    LowGainOverflow: 65535

    ### ROOT::TF1 expression for calibrations
    #HighGainXAFormula: "1.0*x"
    #HighGainXBFormula: "1.0*x"
    #HighGainYAFormula: "1.0*x"
    #HighGainYBFormula: "1.0*x"
    #LowGainXAFormula: "1.0*x"
    #LowGainXBFormula: "1.0*x"
    #LowGainYAFormula: "1.0*x"
    #LowGainYBFormula: "1.0*x"
    #HighGainPosXFormula: "1.0*x"
    #HighGainPosYFormula: "1.0*x"
    #LowGainPosXFormula: "1.0*x"
    #LowGainPosYFormula: "1.0*x"
